### ISSUE TITLE
How should I set the Matomo configuration values & what permissions does my Matomo user need for the auth token?

### ISSUE THREAD

**Issue by ghost** [wintercms/wn-matomo-plugin#8]
I am editing /var/www/winter/plugins/winter/matomo/config/config.php and it's unclear to me if I have setup it correctly.

My server: https://matomo.example.com/
My site id: 1
My auth_token: xxxxxxxxxxxxxxxxxxxxxxxxxxx

Is this OK or should something be changed?:

`'server' => env('MATOMO_SERVER', 'https://matomo.example.com/'),`
`'site_id' => env('MATOMO_SITE_ID', 1),`
`'auth_token' => env('MATOMO_TOKEN', 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'),`

Another thing it's unclear what permissions should matomo user for token have: I am guessing at least write or it will not work.
Here is what permissions we can assign to the user:
![permissions](https://user-images.githubusercontent.com/56940608/178213611-90db7dad-222f-44c8-928a-6500c151af99.png)

**Comment by LukeTowers** [comment]
If you're just using it for tracking events then you should only need View access. You might need write access in order to embed the Matomo reporting widgets on your backend dashboard.

Don't change the plugin's config file directly though, either use a .env file and provide the values through the environment variables specified or copy the config file to `myproject/config/winter/matomo/config.php` and change the values there.

**Comment by ghost** [comment]
Thanks @LukeTowers and Romain 'Maz' B. from discord for helping.

The correct location for config file in my case is /var/www/winter/config/winter/matomo/config.php (you need to create the folders if they are not created already.

Correct config.php

` 'server' => 'https://matomo.example.com/',`

`'site_id' => 1,`

`'auth_token' => 'xxxx', `

you only need apostrophe for string values that was a bit confusing for me. all makes sense now.
